CREATE ROLE IF NOT EXISTS ADMIN_ETL_ROLE;
GRANT ROLE ADMIN_ETL_ROLE TO ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS GU_ETL_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
