-- minimum roles
CREATE ROLE IF NOT EXISTS ADMIN_ETL_ROLE;
GRANT ROLE ADMIN_ETL_ROLE TO ROLE SYSADMIN;

-- CREATE an economic data warehouse
CREATE WAREHOUSE IF NOT EXISTS GU_ETL_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Base y esquemas
CREATE DATABASE IF NOT EXISTS RETAIL_DW;
CREATE SCHEMA IF NOT EXISTS RETAIL_DW.RAW;
CREATE SCHEMA IF NOT EXISTS RETAIL_DW.STG;
CREATE SCHEMA IF NOT EXISTS RETAIL_DW.CORE;
CREATE SCHEMA IF NOT EXISTS RETAIL_DW.MART;

-- Usos
USE ROLE ADMIN_ETL_ROLE;
USE WAREHOUSE GU_ETL_WH;
USE DATABASE RETAIL_DW;