USE DATABASE RETAIL_DW;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE DIM_PRODUCT (
    product_id INT AUTOINCREMENT PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    category VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_SALES_REP (
    sales_rep_id INT AUTOINCREMENT PRIMARY KEY,
    sales_rep_name VARCHAR(255) NOT NULL
);

CREATE OR REPLACE TABLE DIM_REGION (
    region_id INT AUTOINCREMENT PRIMARY KEY,
    region_name VARCHAR(100) NOT NULL
);

CREATE OR REPLACE TABLE DIM_DATE (
    date_id DATE PRIMARY KEY,
    year INT,
    month INT,
    day INT
);