USE DATABASE RETAIL_DW;
USE SCHEMA STG;

CREATE OR REPLACE TABLE RAW_SALES (
    PRODUCT_ID INT,
    SALE_DATE STRING,
    SALES_REP STRING,
    REGION STRING,
    AMOUNT_SOLD FLOAT,
    QUANTITY_SOLD INT,
    PRODUCT_CATEGORY STRING,
    UNIT_COST FLOAT,
    UNIT_PRICE FLOAT,
    CUSTOMER_TYPE STRING,
    DISCOUNT FLOAT,
    PAYMENT_METHOD STRING,
    SALES_CHANNEL STRING,
    REGION_AND_SALES_REP STRING
);
