USE DATABASE RETAIL_DW;
USE SCHEMA RAW;

MERGE INTO DIM_REGION AS tgt
USING (
  SELECT DISTINCT
    UPPER(TRIM(REGION)) AS REGION_NAME
  FROM STG.RAW_SALES
  WHERE REGION IS NOT NULL AND TRIM(REGION) <> ''
) AS src
ON tgt.REGION_NAME = src.REGION_NAME
WHEN NOT MATCHED THEN
  INSERT (REGION_NAME) VALUES (src.REGION_NAME);
