USE DATABASE RETAIL_DW;
USE SCHEMA RAW;

MERGE INTO DIM_REGION AS tgt
USING (
  SELECT DISTINCT
    UPPER(TRIM(REGION)) AS REGION_NAME
  FROM STG.RAW_SALES
  WHERE REGION IS NOT NULL AND TRIM(REGION) <> ''
) AS src
ON tgt.REGION_NAME = src.REGION_NAME
WHEN NOT MATCHED THEN
  INSERT (REGION_NAME) VALUES (src.REGION_NAME);

MERGE INTO DIM_PRODUCT AS tgt
USING (
    SELECT DISTINCT
        PRODUCT_ID,
        PRODUCT_CATEGORY,
        UNIT_COST,
        UNIT_PRICE
    FROM STG.RAW_SALES
    WHERE PRODUCT_ID IS NOT NULL
) AS src
ON tgt.PRODUCT_ID = src.PRODUCT_ID

WHEN MATCHED THEN
    UPDATE SET 
        tgt.PRODUCT_CATEGORY = src.PRODUCT_CATEGORY,
        tgt.UNIT_COST = src.UNIT_COST,
        tgt.UNIT_PRICE = src.UNIT_PRICE

WHEN NOT MATCHED THEN
    INSERT (PRODUCT_ID, PRODUCT_CATEGORY, UNIT_COST, UNIT_PRICE)
    VALUES (src.PRODUCT_ID, src.PRODUCT_CATEGORY, src.UNIT_COST, src.UNIT_PRICE);